<a href="https://colab.research.google.com/github/IrigoyenCodes/Artificial-Intelligence/blob/main/StatsNBAPredictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NBA SEASON LEADERS

In [ ]:
# Data Processing
import pandas as pd
import numpy as np


# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz

pd.set_option('display.max_columns', None)
import time
import requests

In [ ]:
test_url1 = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=PerGame&Scope=S&Season=2024-25&SeasonType=Regular%20Season&StatCategory=PTS'

In [ ]:
r = requests.get(url = test_url1).json()

In [ ]:
table_headers = r['resultSet']['headers']

In [ ]:
pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PTS,EFF
0,1628983,1,Shai Gilgeous-Alexander,1610612760,OKC,75,34.1,11.3,21.7,0.519,2.1,5.7,0.371,7.9,8.8,0.900,0.9,4.1,5.0,6.4,1.7,1.0,2.4,32.6,32.9
1,203507,2,Giannis Antetokounmpo,1610612749,MIL,64,34.2,11.9,19.8,0.602,0.2,0.9,0.211,6.5,10.5,0.618,2.2,9.7,11.9,6.3,0.9,1.2,3.2,30.5,35.7
2,203999,3,Nikola JokiÄ‡,1610612743,DEN,67,36.7,11.4,19.7,0.577,2.0,4.8,0.415,5.2,6.4,0.803,2.9,9.9,12.8,10.2,1.8,0.7,3.3,30.0,42.4
3,1630162,4,Anthony Edwards,1610612750,MIN,75,36.3,9.1,20.3,0.446,4.0,10.2,0.397,5.3,6.3,0.835,0.8,4.9,5.7,4.6,1.1,0.6,3.2,27.4,23.9
4,1628369,5,Jayson Tatum,1610612738,BOS,70,36.3,9.2,20.4,0.452,3.5,10.1,0.344,5.0,6.2,0.814,0.7,8.0,8.7,6.0,1.1,0.5,3.0,26.9,27.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,1631200,233,Kris Murray,1610612757,POR,66,14.4,1.6,3.8,0.434,0.4,1.6,0.243,0.3,0.8,0.431,1.0,1.5,2.5,0.9,0.5,0.2,0.6,4.0,4.9
233,203500,234,Steven Adams,1610612745,HOU,57,13.6,1.6,2.9,0.546,0.0,0.0,0.000,0.8,1.6,0.462,2.9,2.8,5.6,1.1,0.4,0.5,0.9,3.9,8.4
234,201587,235,Nicolas Batum,1610612746,LAC,76,17.6,1.3,3.0,0.423,1.1,2.5,0.420,0.2,0.3,0.800,0.6,2.2,2.8,1.1,0.7,0.5,0.4,3.8,6.7
235,1641748,236,Andre Jackson Jr.,1610612749,MIL,65,14.4,1.3,2.9,0.463,0.4,1.2,0.387,0.2,0.3,0.545,1.0,1.8,2.8,1.2,0.5,0.2,0.8,3.3,5.5
236,1630192,237,Zeke Nnaji,1610612743,DEN,56,10.8,1.3,2.5,0.500,0.3,0.9,0.333,0.5,0.8,0.619,0.6,1.0,1.6,0.4,0.4,0.7,0.3,3.3,4.6

Warning: Total number of columns (25) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df = pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)
df.to_csv('nba_stats.csv', index=False)

# NBA BOX SCORES IND TEAMS & LEADERS

In [ ]:
import requests
import pandas as pd

url = "https://stats.nba.com/stats/leaguegamelog?Counter=1000&DateFrom=&DateTo=&Direction=DESC&ISTRound=&LeagueID=00&PlayerOrTeam=P&Season=2024-25&SeasonType=Regular%20Season&Sorter=DATE"
# Parameters matching your URL
params = {
    "Conference": "",
    "DateFrom": "",
    "DateTo": "",
    "Division": "",
    "GameScope": "",
    "GameSegment": "",
    "Height": "",
    "ISTRound": "",
    "LastNGames": "0",
    "LeagueID": "00",
    "Location": "",
    "MeasureType": "Base",
    "Month": "0",
    "OpponentTeamID": "0",
    "Outcome": "",
    "PORound": "0",
    "PaceAdjust": "N",
    "PerMode": "Totals",
    "Period": "0",
    "PlayerExperience": "",
    "PlayerPosition": "",
    "PlusMinus": "N",
    "Rank": "N",
    "Season": "2024-25",
    "SeasonSegment": "",
    "SeasonType": "Regular Season",
    "ShotClockRange": "",
    "StarterBench": "",
    "TeamID": "0",
    "TwoWay": "0",
    "VsConference": "",
    "VsDivision": ""
}

# NBA API often requires specific headers to mimic a browser
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Referer": "https://stats.nba.com/",
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-US,en;q=0.9",
    "x-nba-stats-origin": "stats",
    "x-nba-stats-token": "true"
}

response = requests.get(url, params=params, headers=headers)

# Check if successful
if response.status_code == 200:
    data = response.json()
    # Extract headers and rows
    headers = data['resultSets'][0]['headers']
    rows = data['resultSets'][0]['rowSet']
    # Create DataFrame
    df = pd.DataFrame(rows, columns=headers)
    # Save to CSV
    df.to_csv('nba_team_stats_2024_25.csv', index=False)
    print("Data successfully saved to CSV!")
else:
    print(f"Error: {response.status_code}")
    print(response.text)

Data successfully saved to CSV!

In [ ]:
from IPython.display import display
display(df)

,SEASON_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,FANTASY_PTS,VIDEO_AVAILABLE
0,22024,1630542,Marcus Bagley,1610612755,PHI,Philadelphia 76ers,0022401145,2025-04-07,PHI @ MIA,L,23,2,8,0.250,0,2,0.000,2,2,1.000,2,4,6,0,1,1,1,1,6,-2,18.2,1
1,22024,201942,DeMar DeRozan,1610612758,SAC,Sacramento Kings,0022401144,2025-04-07,SAC @ DET,W,37,14,26,0.538,1,6,0.167,8,10,0.800,1,3,4,2,0,1,2,3,37,15,45.8,1
2,22024,203471,Dennis SchrÃ¶der,1610612765,DET,Detroit Pistons,0022401144,2025-04-07,DET vs. SAC,L,32,1,4,0.250,1,2,0.500,2,4,0.500,1,2,3,2,0,0,1,2,5,-19,10.6,1
3,22024,203501,Tim Hardaway Jr.,1610612765,DET,Detroit Pistons,0022401144,2025-04-07,DET vs. SAC,L,35,6,15,0.400,4,11,0.364,3,3,1.000,0,0,0,2,0,0,2,0,19,-17,20.0,1
4,22024,203926,Doug McDermott,1610612758,SAC,Sacramento Kings,0022401144,2025-04-07,SAC @ DET,W,3,0,0,NaN,0,0,NaN,0,0,NaN,0,1,1,0,0,0,0,0,0,-3,1.2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25153,22024,1630162,Anthony Edwards,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,41,10,25,0.400,5,13,0.385,2,3,0.667,0,6,6,3,0,0,4,3,27,0,34.7,1
25154,22024,1630559,Austin Reaves,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,36,6,14,0.429,0,5,0.000,0,1,0.000,4,5,9,4,1,1,0,4,12,12,34.8,1
25155,22024,1631108,Max Christie,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,11,0,3,0.000,0,3,0.000,2,2,1.000,1,1,2,0,0,0,0,5,2,-5,4.4,1
25156,22024,1642355,Bronny James,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,3,0,2,0.000,0,1,0.000,0,0,NaN,1,0,1,0,0,0,0,0,0,-5,1.2,1
25157,22024,1628404,Josh Hart,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,25,4,6,0.667,0,2,0.000,4,6,0.667,1,3,4,3,0,0,1,0,12,-23,20.3,1

Warning: Total number of columns (32) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (25158) exceeds max_rows (20000). Limiting to first (20000) rows.

# NBA BOX SCORES IND PLAYERS LAST 4 GAMES

In [ ]:
import requests
import pandas as pd

# URL to fetch NBA stats
url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&ISTRound=&LastNGames=4&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2024-25&SeasonSegment=&SeasonType=Regular%20Season&ShotClockRange=&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight='
params = {
    'College': '',
    'Conference': '',
    'Country': '',
    'DateFrom': '',
    'DateTo': '',
    'Division': '',
    'DraftPick': '',
    'DraftYear': '',
    'GameScope': '',
    'GameSegment': '',
    'Height': '',
    'ISTRound': '',
    'LastNGames': '4',
    'LeagueID': '00',
    'Location': '',
    'MeasureType': 'Base',
    'Month': '0',
    'OpponentTeamID': '0',
    'Outcome': '',
    'PORound': '0',
    'PaceAdjust': 'N',
    'PerMode': 'PerGame',
    'Period': '0',
    'PlayerExperience': '',
    'PlayerPosition': '',
    'PlusMinus': 'N',
    'Rank': 'N',
    'Season': '2024-25',
    'SeasonSegment': '',
    'SeasonType': 'Regular Season',
    'ShotClockRange': '',
    'StarterBench': '',
    'TeamID': '0',
    'VsConference': '',
    'VsDivision': '',
    'Weight': ''
}

# Headers to simulate a browser request
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    'Referer': 'https://www.nba.com/',
    'Origin': 'https://www.nba.com',
    'Accept': 'application/json',
    'x-nba-stats-origin': 'stats',
    'x-nba-stats-token': 'true'
}

# Make the request
response = requests.get(url, headers=headers, params=params)
data = response.json()

# Extract headers and rows
columns = data['resultSets'][0]['headers']
rows = data['resultSets'][0]['rowSet']

# Convert to DataFrame
df = pd.DataFrame(rows, columns=columns)

In [ ]:
from IPython.display import display
display(df)

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1610612737,Atlanta Hawks,78,37,41,0.474,3764.0,3376,7174,0.471,1045,2930,0.357,1408,1811,0.777,926,2534,3460,2305,1209.0,763,405,384,1489,1492,9205,-136.0,11,18,17,18,16,8,4,14,14,16,18,5,6,19,9,23,15,2,25,2,11,15,17,9,5,19
1,1610612738,Boston Celtics,78,58,20,0.744,3769.0,3257,7028,0.463,1394,3770,0.370,1208,1509,0.801,890,2644,3534,2041,919.0,555,429,278,1250,1378,9116,722.0,11,3,3,3,14,16,13,18,1,1,9,30,30,6,11,10,9,16,1,29,5,1,2,27,9,3
2,1610612751,Brooklyn Nets,78,25,53,0.321,3764.0,2938,6723,0.437,1050,3064,0.343,1269,1608,0.789,856,2367,3223,1957,1180.0,609,343,442,1602,1473,8195,-530.0,11,25,25,25,16,30,27,29,13,8,27,24,25,11,18,29,29,24,23,21,26,27,27,13,30,26
3,1610612766,Charlotte Hornets,78,19,59,0.244,3759.0,3001,6967,0.431,1017,2991,0.340,1223,1554,0.787,962,2566,3528,1901,1203.0,582,353,416,1474,1429,8242,-650.0,11,28,28,28,19,28,18,30,19,11,28,29,28,13,6,19,10,26,24,26,21,23,16,22,28,27
4,1610612741,Chicago Bulls,78,36,42,0.462,3759.0,3366,7174,0.469,1211,3286,0.369,1244,1543,0.806,775,2781,3556,2263,1141.0,586,365,400,1385,1318,9187,-164.0,11,19,19,19,19,9,4,15,3,3,11,28,29,3,25,1,6,5,20,25,18,18,6,30,6,20
5,1610612739,Cleveland Cavaliers,78,62,16,0.795,3749.0,3476,7054,0.493,1232,3223,0.382,1342,1715,0.783,859,2655,3514,2201,1021.0,638,333,335,1416,1484,9526,764.0,11,2,2,2,27,3,12,2,2,4,2,14,13,15,17,7,12,9,3,13,28,5,9,12,2,2
6,1610612742,Dallas Mavericks,79,38,41,0.481,3802.0,3320,6946,0.478,991,2713,0.365,1415,1832,0.772,797,2601,3398,1986,1093.0,616,426,364,1419,1486,9046,-70.0,1,16,17,17,10,12,20,11,23,25,14,3,1,23,24,14,21,21,12,20,6,12,11,11,12,18
7,1610612743,Denver Nuggets,79,47,32,0.595,3827.0,3592,7095,0.506,956,2532,0.378,1395,1816,0.768,885,2722,3607,2452,1140.0,633,389,406,1398,1492,9535,288.0,1,7,8,8,3,1,9,1,27,30,5,6,3,24,12,3,3,1,18,17,14,20,7,9,1,9
8,1610612765,Detroit Pistons,79,43,36,0.544,3812.0,3359,7081,0.474,1003,2781,0.361,1383,1776,0.779,900,2651,3551,2080,1179.0,637,414,392,1634,1498,9104,160.0,1,14,14,14,6,10,10,13,20,23,17,7,10,18,10,8,7,14,22,14,10,16,29,7,10,12
9,1610612744,Golden State Warriors,78,46,32,0.590,3749.0,3185,7071,0.450,1204,3310,0.364,1291,1698,0.760,984,2565,3549,2269,1094.0,723,373,424,1503,1440,8865,224.0,11,9,8,9,27,22,11,25,4,2,16,21,18,26,5,20,8,4,13,5,17,24,22,21,18,10
10,1610612745,Houston Rockets,79,52,27,0.658,3812.0,3353,7381,0.454,988,2813,0.351,1341,1815,0.739,1170,2686,3856,1836,1096.0,669,398,457,1502,1538,9035,433.0,1,4,4,4,6,11,1,23,24,20,21,15,4,30,1,5,1,28,15,9,13,28,21,3,13,4
11,1610612754,Indiana Pacers,78,47,31,0.603,3769.0,3410,6938,0.491,1036,2787,0.372,1309,1654,0.791,698,2532,3230,2298,1030.0,661,415,335,1462,1447,9165,181.0,11,7,7,7,14,5,21,3,15,21,7,18,20,9,29,24,28,3,4,10,9,5,15,19,7,11
12,1610612746,LA Clippers,78,46,32,0.590,3764.0,3225,6728,0.479,968,2620,0.369,1357,1705,0.796,800,2619,3419,1954,1163.0,740,362,337,1438,1390,8775,354.0,11,9,8,9,16,17,25,8,26,29,10,11,15,7,23,13,17,25,21,3,20,7,14,26,21,7
13,1610612747,Los Angeles Lakers,78,48,30,0.615,3754.0,3193,6670,0.479,1034,2840,0.364,1425,1805,0.789,748,2563,3311,2039,1080.0,597,349,322,1348,1503,8845,98.0,11,6,6,6,22,20,30,10,16,18,15,2,7,10,27,21,26,17,10,24,22,4,5,6,19,14
14,1610612763,Memphis Grizzlies,78,46,32,0.590,3749.0,3489,7277,0.479,1076,2932,0.367,1436,1827,0.786,1008,2688,3696,2224,1231.0,688,445,438,1632,1580,9490,363.0,11,9,8,9,27,2,2,7,12,15,12,1,2,14,3,4,2,8,28,6,3,26,28,2,3,6
15,1610612748,Miami Heat,79,36,43,0.456,3842.0,3167,6844,0.463,1082,2950,0.367,1271,1603,0.793,762,2651,3413,2074,1084.0,637,300,370,1240,1346,8687,6.0,1,19,20,20,1,25,23,19,11,13,13,23,26,8,26,8,19,15,11,14,30,13,1,29,24,16
16,1610612749,Milwaukee Bucks,78,44,34,0.564,3754.0,3263,6728,0.485,1091,2839,0.384,1344,1791,0.750,642,2746,3388,1976,1045.0,568,363,300,1403,1473,8961,158.0,11,13,13,13,22,14,25,5,10,19,1,13,8,28,30,2,23,22,6,27,19,2,8,13,14,13
17,1610612750,Minnesota Timberwolves,78,46,32,0.590,3774.0,3187,6831,0.467,1176,3111,0.378,1345,1707,0.788,866,2583,3449,2038,1131.0,630,386,358,1422,1495,8895,364.0,11,9,8,9,12,21,24,16,5,6,4,12,14,12,15,15,16,18,17,19,15,11,12,8,15,5
18,1610612740,New Orleans Pelicans,78,21,57,0.269,3759.0,3179,7004,0.454,938,2684,0.349,1281,1699,0.754,946,2446,3392,2016,1140.0,671,417,411,1425,1394,8577,-679.0,11,27,27,27,19,23,16,24,28,26,23,22,17,27,7,27,22,20,18,8,7,22,13,25,26,28
19,1610612752,New York Knicks,78,50,28,0.641,3779.0,3390,6950,0.488,977,2639,0.370,1299,1620,0.802,842,2494,3336,2145,1037.0,631,307,392,1324,1473,9056,345.0,11,5,5,5,11,7,19,4,25,28,8,19,23,5,19,25,24,11,5,18,29,16,4,13,11,8
20,1610612760,Oklahoma City Thunder,78,64,14,0.821,3749.0,3466,7212,0.481,1129,3017,0.374,1299,1585,0.820,826,2657,3483,2095,922.0,807,450,376,1545,1420,9360,977.0,11,1,1,1,27,4,3,6,6,10,6,19,27,1,21,6,14,12,2,1,2,14,25,24,4,1
21,1610612753,Orlando Magic,78,38,40,0.487,3754.0,2962,6686,0.443,863,2746,0.314,1409,1815,0.776,869,2392,3261,1784,1106.0,686,463,341,1583,1595,8196,-39.0,11,16,15,16,22,29,29,27,30,24,30,4,4,20,13,28,27,30,16,7,1,8,26,1,29,17
22,1610612755,Philadelphia 76ers,79,23,56,0.291,3817.0,3136,6886,0.455,1001,2921,0.343,1381,1770,0.780,810,2305,3115,1832,1070.0,729,346,409,1504,1473,8654,-496.0,1,26,26,26,4,26,22,21,21,17,26,8,11,16,22,30,30,29,8,4,25,21,23,13,25,25
23,1610612756,Phoenix Suns,78,35,43,0.449,3774.0,3220,6721,0.479,1115,2936,0.380,1340,1651,0.812,739,2577,3316,2169,1095.0,556,374,318,1417,1467,8895,-203.0,11,21,20,21,12,18,28,9,7,14,3,17,21,2,28,16,25,10,14,28,16,3,10,18,15,21
24,1610612757,Portland Trail Blazers,79,35,44,0.443,3807.0,3203,7111,0.450,1025,2978,0.344,1341,1749,0.767,1041,2479,3520,1877,1254.0,649,417,431,1499,1515,8772,-248.0,1,21,22,22,9,19,8,26,18,12,25,15,12,25,2,26,11,27,29,11,7,25,19,5,22,23
25,1610612758,Sacramento Kings,79,39,40,0.494,3832.0,3403,7120,0.478,992,2786,0.356,1367,1701,0.804,869,2629,3498,2090,1060.0,607,347,343,1501,1471,9165,37.0,1,15,15,15,2,6,7,12,22,22,19,10,16,4,13,12,13,13,7,22,24,9,20,17,7,15
26,1610612759,San Antonio Spurs,78,32,46,0.410,3754.0,3260,7022,0.464,1099,3092,0.355,1269,1642,0.773,864,2550,3414,2246,1079.0,641,442,343,1304,1363,8888,-212.0,11,23,23,23,22,15,14,17,8,7,20,24,22,22,16,22,18,7,9,12,4,9,3,28,17,22
27,1610612761,Toronto Raptors,79,29,50,0.367,3817.0,3279,7161,0.458,925,2656,0.348,1262,1683,0.750,990,2570,3560,2249,1224.0,637,341,469,1684,1446,8745,-353.0,1,24,24,24,4,13,6,20,29,27,24,26,19,29,4,18,5,6,27,14,27,29,30,20,23,24
28,1610612762,Utah Jazz,79,16,63,0.203,3812.0,3176,6982,0.455,1096,3126,0.351,1378,1783,0.773,939,2632,3571,2019,1358.0,528,348,509,1494,1524,8826,-728.0,1,30,30,30,6,24,17,22,9,5,22,9,9,21,8,11,4,19,30,30,23,30,18,4,20,29
29,1610612764,Washington Wizards,78,17,61,0.218,3754.0,3080,7012,0.439,1028,3060,0.336,1259,1616,0.779,827,2575,3402,1959,1216.0,601,402,402,1536,1429,8447,-966.0,11,29,29,29,22,27,15,28,17,9,29,27,24,17,20,17,20,23,26,23,12,19,24,22,27,30

Warning: Total number of columns (54) exceeds max_columns (20) limiting to first (20) columns.

# NBA ALL SEASON TEAM STATS

In [ ]:
import requests
import pandas as pd

url = "https://stats.nba.com/stats/leaguedashteamstats?Conference=&DateFrom=&DateTo=&Division=&GameScope=&GameSegment=&Height=&ISTRound=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2024-25&SeasonSegment=&SeasonType=Regular%20Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision="

# Parameters matching your URL
params = {
    "Conference": "",
    "DateFrom": "",
    "DateTo": "",
    "Division": "",
    "GameScope": "",
    "GameSegment": "",
    "Height": "",
    "ISTRound": "",
    "LastNGames": "0",
    "LeagueID": "00",
    "Location": "",
    "MeasureType": "Base",
    "Month": "0",
    "OpponentTeamID": "0",
    "Outcome": "",
    "PORound": "0",
    "PaceAdjust": "N",
    "PerMode": "Totals",
    "Period": "0",
    "PlayerExperience": "",
    "PlayerPosition": "",
    "PlusMinus": "N",
    "Rank": "N",
    "Season": "2024-25",
    "SeasonSegment": "",
    "SeasonType": "Regular Season",
    "ShotClockRange": "",
    "StarterBench": "",
    "TeamID": "0",
    "TwoWay": "0",
    "VsConference": "",
    "VsDivision": ""
}

# NBA API often requires specific headers to mimic a browser
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Referer": "https://stats.nba.com/",
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-US,en;q=0.9",
    "x-nba-stats-origin": "stats",
    "x-nba-stats-token": "true"
}

response = requests.get(url, params=params, headers=headers)

# Check if successful
if response.status_code == 200:
    data = response.json()
    # Extract headers and rows
    headers = data['resultSets'][0]['headers']
    rows = data['resultSets'][0]['rowSet']
    # Create DataFrame
    df = pd.DataFrame(rows, columns=headers)
    # Save to CSV
    df.to_csv('nba_team_stats_2024_25.csv', index=False)
    print("Data successfully saved to CSV!")
else:
    print(f"Error: {response.status_code}")
    print(response.text)

Data successfully saved to CSV!

In [ ]:
from IPython.display import display
display(df)

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1610612737,Atlanta Hawks,78,37,41,0.474,3764.0,3376,7174,0.471,1045,2930,0.357,1408,1811,0.777,926,2534,3460,2305,1209.0,763,405,384,1489,1492,9205,-136.0,7,18,17,18,15,7,4,14,14,15,18,5,6,19,9,23,14,2,25,2,11,15,18,8,5,19
1,1610612738,Boston Celtics,78,58,20,0.744,3769.0,3257,7028,0.463,1394,3770,0.370,1208,1509,0.801,890,2644,3534,2041,919.0,555,429,278,1250,1378,9116,722.0,7,3,3,3,12,16,12,18,1,1,9,30,30,6,10,8,8,16,1,29,5,1,2,27,8,3
2,1610612751,Brooklyn Nets,78,25,53,0.321,3764.0,2938,6723,0.437,1050,3064,0.343,1269,1608,0.789,856,2367,3223,1957,1180.0,609,343,442,1602,1473,8195,-530.0,7,25,25,25,15,30,27,29,13,8,27,23,25,11,17,29,29,24,23,21,24,27,27,13,30,26
3,1610612766,Charlotte Hornets,78,19,59,0.244,3759.0,3001,6967,0.431,1017,2991,0.340,1223,1554,0.787,962,2566,3528,1901,1203.0,582,353,416,1474,1429,8242,-650.0,7,28,28,28,19,28,18,30,19,11,28,29,28,13,6,19,9,26,24,26,21,23,16,22,28,27
4,1610612741,Chicago Bulls,78,36,42,0.462,3759.0,3366,7174,0.469,1211,3286,0.369,1244,1543,0.806,775,2781,3556,2263,1141.0,586,365,400,1385,1318,9187,-164.0,7,19,19,19,19,8,4,15,3,3,11,28,29,3,25,1,6,5,20,25,18,18,6,30,6,20
5,1610612739,Cleveland Cavaliers,78,62,16,0.795,3749.0,3476,7054,0.493,1232,3223,0.382,1342,1715,0.783,859,2655,3514,2201,1021.0,638,333,335,1416,1484,9526,764.0,7,2,2,2,27,3,10,2,2,4,2,14,13,15,16,7,11,9,3,13,28,5,9,11,2,2
6,1610612742,Dallas Mavericks,79,38,41,0.481,3802.0,3320,6946,0.478,991,2713,0.365,1415,1832,0.772,797,2601,3398,1986,1093.0,616,426,364,1419,1486,9046,-70.0,1,15,17,17,6,11,20,11,20,25,14,3,1,23,23,13,20,21,12,20,6,12,11,10,10,18
7,1610612743,Denver Nuggets,79,47,32,0.595,3827.0,3592,7095,0.506,956,2532,0.378,1395,1816,0.768,885,2722,3607,2452,1140.0,633,389,406,1398,1492,9535,288.0,1,7,8,8,1,1,8,1,27,30,5,6,3,24,12,3,3,1,18,15,14,21,7,8,1,9
8,1610612765,Detroit Pistons,78,43,35,0.551,3764.0,3317,6992,0.474,990,2742,0.361,1363,1748,0.780,887,2627,3514,2050,1170.0,629,409,388,1611,1477,8987,170.0,7,14,14,14,15,12,16,13,21,24,17,9,11,17,11,10,11,14,22,19,10,16,28,12,13,12
9,1610612744,Golden State Warriors,78,46,32,0.590,3749.0,3185,7071,0.450,1204,3310,0.364,1291,1698,0.760,984,2565,3549,2269,1094.0,723,373,424,1503,1440,8865,224.0,7,9,8,9,27,22,9,25,4,2,16,21,17,26,5,20,7,4,13,4,17,24,23,21,18,10
10,1610612745,Houston Rockets,79,52,27,0.658,3812.0,3353,7381,0.454,988,2813,0.351,1341,1815,0.739,1170,2686,3856,1836,1096.0,669,398,457,1502,1538,9035,433.0,1,4,4,4,3,10,1,23,23,20,21,15,4,30,1,5,1,28,15,9,13,28,22,3,12,4
11,1610612754,Indiana Pacers,78,47,31,0.603,3769.0,3410,6938,0.491,1036,2787,0.372,1309,1654,0.791,698,2532,3230,2298,1030.0,661,415,335,1462,1447,9165,181.0,7,7,7,7,12,5,21,3,15,21,7,18,20,9,29,24,28,3,4,10,9,5,15,19,7,11
12,1610612746,LA Clippers,78,46,32,0.590,3764.0,3225,6728,0.479,968,2620,0.369,1357,1705,0.796,800,2619,3419,1954,1163.0,740,362,337,1438,1390,8775,354.0,7,9,8,9,15,17,25,8,26,29,10,10,15,7,22,11,17,25,21,3,20,7,14,26,21,7
13,1610612747,Los Angeles Lakers,78,48,30,0.615,3754.0,3193,6670,0.479,1034,2840,0.364,1425,1805,0.789,748,2563,3311,2039,1080.0,597,349,322,1348,1503,8845,98.0,7,6,6,6,22,20,30,10,16,18,15,2,7,10,27,21,26,17,11,24,22,4,5,6,19,14
14,1610612763,Memphis Grizzlies,78,46,32,0.590,3749.0,3489,7277,0.479,1076,2932,0.367,1436,1827,0.786,1008,2688,3696,2224,1231.0,688,445,438,1632,1580,9490,363.0,7,9,8,9,27,2,2,7,11,14,12,1,2,14,3,4,2,8,28,6,3,26,29,2,3,6
15,1610612748,Miami Heat,78,35,43,0.449,3794.0,3122,6755,0.462,1066,2914,0.366,1260,1588,0.793,752,2614,3366,2048,1071.0,630,294,366,1223,1332,8570,-6.0,7,20,20,20,7,25,24,19,12,16,13,26,26,8,26,12,23,15,9,17,30,13,1,29,25,16
16,1610612749,Milwaukee Bucks,78,44,34,0.564,3754.0,3263,6728,0.485,1091,2839,0.384,1344,1791,0.750,642,2746,3388,1976,1045.0,568,363,300,1403,1473,8961,158.0,7,13,13,13,22,14,25,5,10,19,1,13,8,28,30,2,22,22,6,27,19,2,8,13,14,13
17,1610612750,Minnesota Timberwolves,78,46,32,0.590,3774.0,3187,6831,0.467,1176,3111,0.378,1345,1707,0.788,866,2583,3449,2038,1131.0,630,386,358,1422,1495,8895,364.0,7,9,8,9,10,21,22,16,5,6,4,11,14,12,14,15,15,18,17,17,15,11,12,7,15,5
18,1610612740,New Orleans Pelicans,78,21,57,0.269,3759.0,3179,7004,0.454,938,2684,0.349,1281,1699,0.754,946,2446,3392,2016,1140.0,671,417,411,1425,1394,8577,-679.0,7,27,27,27,19,23,15,24,28,26,23,22,16,27,7,27,21,20,18,8,7,22,13,25,24,28
19,1610612752,New York Knicks,78,50,28,0.641,3779.0,3390,6950,0.488,977,2639,0.370,1299,1620,0.802,842,2494,3336,2145,1037.0,631,307,392,1324,1473,9056,345.0,7,5,5,5,9,6,19,4,25,28,8,19,23,5,19,25,24,11,5,16,29,17,4,13,9,8
20,1610612760,Oklahoma City Thunder,78,64,14,0.821,3749.0,3466,7212,0.481,1129,3017,0.374,1299,1585,0.820,826,2657,3483,2095,922.0,807,450,376,1545,1420,9360,977.0,7,1,1,1,27,4,3,6,6,10,6,19,27,1,21,6,13,12,2,1,2,14,25,24,4,1
21,1610612753,Orlando Magic,78,38,40,0.487,3754.0,2962,6686,0.443,863,2746,0.314,1409,1815,0.776,869,2392,3261,1784,1106.0,686,463,341,1583,1595,8196,-39.0,7,15,15,15,22,29,29,27,30,23,30,4,4,20,13,28,27,30,16,7,1,9,26,1,29,17
22,1610612755,Philadelphia 76ers,78,23,55,0.295,3769.0,3098,6798,0.456,989,2883,0.343,1364,1745,0.782,796,2274,3070,1812,1057.0,722,342,403,1490,1456,8549,-484.0,7,26,26,26,12,26,23,21,22,17,26,8,12,16,24,30,30,29,8,5,26,20,19,17,26,25
23,1610612756,Phoenix Suns,78,35,43,0.449,3774.0,3220,6721,0.479,1115,2936,0.380,1340,1651,0.812,739,2577,3316,2169,1095.0,556,374,318,1417,1467,8895,-203.0,7,20,20,20,10,18,28,9,7,13,3,17,21,2,28,16,25,10,14,28,16,3,10,16,15,21
24,1610612757,Portland Trail Blazers,79,35,44,0.443,3807.0,3203,7111,0.450,1025,2978,0.344,1341,1749,0.767,1041,2479,3520,1877,1254.0,649,417,431,1499,1515,8772,-248.0,1,20,22,22,5,19,7,26,18,12,25,15,10,25,2,26,10,27,29,11,7,25,21,5,22,23
25,1610612758,Sacramento Kings,78,38,40,0.487,3784.0,3356,7029,0.477,981,2759,0.356,1345,1674,0.803,851,2597,3448,2070,1048.0,602,343,338,1480,1448,9038,27.0,7,15,15,15,8,9,11,12,24,22,19,11,19,4,18,14,16,13,7,22,24,8,17,18,11,15
26,1610612759,San Antonio Spurs,78,32,46,0.410,3754.0,3260,7022,0.464,1099,3092,0.355,1269,1642,0.773,864,2550,3414,2246,1079.0,641,442,343,1304,1363,8888,-212.0,7,23,23,23,22,15,13,17,8,7,20,23,22,22,15,22,18,7,10,12,4,10,3,28,17,22
27,1610612761,Toronto Raptors,79,29,50,0.367,3817.0,3279,7161,0.458,925,2656,0.348,1262,1683,0.750,990,2570,3560,2249,1224.0,637,341,469,1684,1446,8745,-353.0,1,24,24,24,2,13,6,20,29,27,24,25,18,29,4,18,5,6,27,14,27,29,30,20,23,24
28,1610612762,Utah Jazz,79,16,63,0.203,3812.0,3176,6982,0.455,1096,3126,0.351,1378,1783,0.773,939,2632,3571,2019,1358.0,528,348,509,1494,1524,8826,-728.0,1,30,30,30,3,24,17,22,9,5,22,7,9,21,8,9,4,19,30,30,23,30,20,4,20,29
29,1610612764,Washington Wizards,78,17,61,0.218,3754.0,3080,7012,0.439,1028,3060,0.336,1259,1616,0.779,827,2575,3402,1959,1216.0,601,402,402,1536,1429,8447,-966.0,7,29,29,29,22,27,14,28,17,9,29,27,24,18,20,17,19,23,26,23,12,19,24,22,27,30

# IGNORE (POSSIBLE CODE NEEDED)

In [ ]:
import requests
import pandas as pd

def get_player_vs_team_stats(player_name, team_abbreviation, season="2024-25"):
    # First, search for the player to get their ID
    player_info_url = "https://stats.nba.com/stats/playerindex"
    player_params = {
        "Historical": "0",
        "LeagueID": "00",
        "Season": season
    }

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
        "Referer": "https://stats.nba.com/",
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "en-US,en;q=0.9",
        "x-nba-stats-origin": "stats",
        "x-nba-stats-token": "true"
    }

    # Get player ID (in a real scenario, we'd search for the player name)
    # For this example, let's use a lookup for Jarrett Allen's player ID
    # Jarrett Allen's player ID is 1628386
    player_id = 1628386  # For Jarrett Allen

    # Get team ID (similar lookup would be done in production)
    # OKC's team ID is 1610612760
    team_id = 1610612760  # For OKC

    # Now get the player vs team stats
    url = "https://stats.nba.com/stats/playergamelogs"
    params = {
        "DateFrom": "",
        "DateTo": "",
        "GameSegment": "",
        "LastNGames": "0",
        "LeagueID": "00",
        "Location": "",
        "MeasureType": "Base",
        "Month": "0",
        "OpponentTeamID": str(team_id),  # Important: filter by opponent team
        "Outcome": "",
        "PORound": "0",
        "PerMode": "Totals",
        "Period": "0",
        "PlayerID": str(player_id),
        "Season": season,
        "SeasonSegment": "",
        "SeasonType": "Regular Season",
        "ShotClockRange": "",
        "TeamID": "0",
        "VsConference": "",
        "VsDivision": ""
    }

    response = requests.get(url, params=params, headers=headers)

    if response.status_code == 200:
        data = response.json()
        # Extract headers and rows
        headers = data['resultSets'][0]['headers']
        rows = data['resultSets'][0]['rowSet']
        # Create DataFrame
        df = pd.DataFrame(rows, columns=headers)
        # Save to CSV
        csv_filename = f"{player_name}_vs_{team_abbreviation}_{season}.csv"
        df.to_csv(csv_filename, index=False)
        print(f"Data saved to {csv_filename}")
        return df
    else:
        print(f"Error: {response.status_code}")
        print(response.text)
        return None

# Get stats for Jarrett Allen vs OKC
allen_vs_okc = get_player_vs_team_stats("Jarrett_Allen", "OKC")

# Print the first few rows
if allen_vs_okc is not None:
    print(allen_vs_okc.head())

    # To download this CSV in Colab
    from google.colab import files
    files.download("Jarrett_Allen_vs_OKC_2024-25.csv")

Player 'Lebron_James' not found in the 2023-24 season.
Could not find player: Lebron_James
No results returned. Check the error messages above.

# RANDOM FOREST CLASSIFIER

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

Training_data = pd.read_csv('nba_stats.csv')

X, y = make_classification(n_samples=1000, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X, y)
print(clf.predict([[0, 0, 0, 0]]))

[1]